### ISSUE TITLE
Why is this not recommended for use in production?

### ISSUE THREAD

**Issue by referentiallytransparent** [lomigmegard/akka-http-cors#2]
Just curious 😄

**Comment by lomigmegard** [comment]
Hi Cal, 

I wrote that at the beginning of the project because I never run this code in production. That said, it doesn't involve any critical part and can therefore safely be tested in your specific use case. 
I will update the project soon to slightly change the defaults settings and update the documentation.

If you have any feedback of running the code in production please send me a message :) 

Cheers, 
Lomig

**Comment by referentiallytransparent** [comment]
Excellent, thanks. Will let you know - so far everything looks great 👍

**Comment by lomigmegard** [comment]
Okay, closing this for now then :-)
Re-open if you have any question.
