### ISSUE TITLE
when testing: Loads settings the wrong way 

### ISSUE THREAD

**Issue by mbknor** [lomigmegard/akka-http-cors#37]
I had great difficulties overriding the settings in a test.

I think this is caused by the default-config is loaded too early:
```scala
val defaultSettings = apply(ConfigFactory.load(getClass.getClassLoader))
``` 
The above works when configuring in the default application.conf, but not in a different config-file used specifically when starting the actor-system. It also does not work to configure it by parsing config string when starting actorSystem.

If I loaded the config like this AFTER the actorSystem had started:
```scala
def corsSettings(actorSystem:ActorSystem):CorsSettings = CorsSettings(actorSystem)
```

Then it used the config that was "current".

(Sorry for the bad explanation)

**Comment by lomigmegard** [comment]
Yes indeed, the `defaultSettings` are eagerly loaded. Your current workaround is correct, pass the settings manually, building them from the actor system

I will address this in a future release, extracting the settings lazily in the directive. Due to some DSL problems, it will bread source compatibility, but I am working on it :)

**Comment by lomigmegard** [comment]
@mbknor almost two years later, the version 1.0.0 fixes this problem :)
